name: Build and Deploy GitHub Pages
on:
  push:
    branch: main
    version: "latest"

 jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Node.js ang build
        run: |
          npm install
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/
    - name: Deploy to GitHub Pages
      runs=o: ubuntu--latest
      steps:
        - name: Deploy
          uses: actions/deploy-pages@v3
          with:
            build_artifact: build-dist
            publish_directory: docs
